/*! Picturefill | Includes: GetViewportWidth, GetDevicePixelWidth, and GetDevicePixelRatio | Author: Tyson Matanich, 2012 | License: MIT/GPLv2 | Based on Picturefill by Scott Jehl and the W3C Picture Element Proposal. */
(function(n){"use strict";var t=[],i=function(n){return n=n.substring(0,n.length-2),Number(n)},f=function(t){var f,u,e;if(t=t==null||t===undefined?"":(t+"").replace(/^[\s]+|[\s]+$/g,""),t.length>0)for(t=t.toLowerCase(),t=t.substring(1,t.length-1),f=t.split(") and ("),u=0,e=f.length;u<e;u++){var o=f[u].indexOf(":"),s=f[u].substring(0,o).replace(/^[\s]+|[\s]+$/g,""),r=f[u].substring(o+1).replace(/^[\s]+|[\s]+$/g,"");switch(s){case"min-width":if(r=i(r),r>n.getViewportWidth())return!1;break;case"max-width":if(r=i(r),r<n.getViewportWidth())return!1;break;case"min-device-pixel-width":if(r=i(r),r>n.getDevicePixelWidth())return!1;break;case"max-device-pixel-width":if(r=i(r),r<n.getDevicePixelWidth())return!1;break;case"min-device-pixel-ratio":if(Number(r)>n.getDevicePixelRatio())return!1;break;default:return!1}}return!0},u=function(t){var o,s,r,u,a,i,l,h,c;for(t.setAttribute("data-resolved","true"),o=t.getElementsByTagName("div"),u=o.length-1;u>=0;u--)if(a=f(o[u].getAttribute("data-media")),a==!0){s=o[u].getAttribute("data-src"),r=u;break}if(i=t.getElementsByTagName("img")[0],s!==undefined){if(l=!1,i){if(h=i.getAttribute("data-source-index"),h==r||t.getAttribute("data-disable-swap-above")!==null&&h>=r||t.getAttribute("data-disable-swap-below")!==null&&h<=r)return}else l=!0,i=n.document.createElement("img"),i.alt=t.getAttribute("data-alt"),t.appendChild(i);l?(i.src=s,i.setAttribute("data-source-index",r)):e(i,s,r)}else i||(c=t.getElementsByTagName("noscript")[0],c!==undefined&&(t.innerHTML=t.innerHTML+(c.innerText||c.innerHTML)))},e=function(i,u,f){if(typeof t[u]=="object"&&t[u].complete)r(i,u,f);else if(document.images){var e=n.document.createElement("img");e.onload=function(){r(i,e.src,f)},e.onerror=function(){o(u,e)},t[u]=e,e.src=u}else r(i,u,f)},r=function(n,t,i){n.src=t,n.setAttribute("data-source-index",i)},o=function(n,i){i.onerror=null,i.onload=null,i.src="",t[n]=undefined};n.picturefill={},n.picturefill.init=function(t){var r,i,f;for(typeof t!="boolean"&&(t=!0),r=n.document.getElementsByTagName("div"),i=0,f=r.length;i<f;i++)r[i]!==undefined&&r[i].getAttribute("data-picture")!==null&&(r[i].getAttribute("data-resolved")===null||r[i].getAttribute("data-disable-swap")===null)&&(t===!0||r[i].getAttribute("data-defer")===null)&&u(r[i])},n.picturefill.resolveLast=function(){for(var i=n.document.getElementsByTagName("div"),t=i.length-1;t>=0;t--)if(i[t].getAttribute("data-picture")!==null&&i[t].getAttribute("data-resolved")===null&&i[t].getAttribute("data-defer")===null){u(i[t]);break}},n.addEventListener?(n.addEventListener("resize",n.picturefill.init,!1),n.addEventListener("DOMContentLoaded",function(){n.picturefill.init(!1),n.removeEventListener("load",n.picturefill.init,!1)},!1),n.addEventListener("load",n.picturefill.init,!1)):n.attachEvent&&n.attachEvent("onload",n.picturefill.init)})(this);

/*! GetViewportWidth | Author: Tyson Matanich, 2012 | License: MIT */
(function(n){n.getViewportWidth=function(){var u,f=n.document,t=f.documentElement,i,r;return n.innerWidth===undefined?u=t.clientWidth:n.innerWidth>t.clientWidth?(i=f.createElement("body"),i.id="vpw-test-b",i.style.cssText="overflow:scroll",r=f.createElement("div"),r.id="vpw-test-d",r.style.cssText="position:absolute;top:-1000px",r.innerHTML="<style>@media(width:"+t.clientWidth+"px){body#vpw-test-b div#vpw-test-d{width:7px!important}}<\/style>",i.appendChild(r),t.insertBefore(i,f.head),u=r.offsetWidth==7?t.clientWidth:n.innerWidth,t.removeChild(i)):u=n.innerWidth,u}})(this);

/*! GetDevicePixelWidth | Includes: GetDevicePixelRatio | Author: Tyson Matanich, 2012 | License: MIT */
(function(n){n.getDevicePixelWidth=function(t){t=t||!1;var i=t==!1||n.screen.width>n.screen.height?n.screen.width:n.screen.height,r=t==!1||n.innerWidth>n.innerHeight?n.innerWidth:n.innerHeight;return r>i&&(i=r),i*n.getDevicePixelRatio()}})(this);

/*! GetDevicePixelRatio | Author: Tyson Matanich, 2012 | License: MIT */
(function(n){n.getDevicePixelRatio=function(){var t=1;return n.screen.systemXDPI!==undefined&&n.screen.logicalXDPI!==undefined&&n.screen.systemXDPI>n.screen.logicalXDPI?t=n.screen.systemXDPI/n.screen.logicalXDPI:n.devicePixelRatio!==undefined&&(t=n.devicePixelRatio),t}})(this);